apiVersion: v1
kind: Service
metadata:
  name: readiness-service
  labels:
    app: readiness-service
spec:
  selector:
    app: readiness
  type: NodePort
  ports:
  - port: 4000
    protocol: TCP
    nodePort: 30063
    