apiVersion: v1
kind: Service
metadata:
  name: simple-node-server-service
  labels:
    app: simple-node-server-service
spec:
  selector:
    app: simple-node-server
  type: NodePort
  ports:
  - port: 4000
    protocol: TCP
    nodePort: 30062