apiVersion: v1
kind: Service
metadata:
  name: liveness-service
  labels:
    app: liveness-service
spec:
  selector:
    app: liveness
  type: NodePort
  ports:
  - port: 4000
    protocol: TCP
    nodePort: 30065
    