apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: liveness-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: liveness
  template:
    metadata:
      labels:
        app: liveness
        version: v1.0.0
    spec:
      containers:
        - name: liveness
          image: matejfistrovic/healthcheck
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          env:
            - name: VERSION
              value: v1.0.0
              