apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: healthz-deployment
spec:
  replicas: 9
  selector:
    matchLabels:
      app: healthz
  template:
    metadata:
      labels:
        app: healthz
        version: v1.0
    spec:
      containers:
        - name: healthz
          image: matejfistrovic/healthz
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          env:
            - name: VERSION
              value: v1.0
          livenessProbe:
            httpGet:
              path: /healthz
              port: 4000
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 4000
            initialDelaySeconds: 3
            periodSeconds: 3