apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: healthz-deployment
spec:
  replicas: 9
  selector:
    matchLabels:
      app: healthz
  template:
    metadata:
      labels:
        app: healthz
        version: v8.0
    spec:
      containers:
        - name: healthz
          image: matejfistrovic/healthz
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          env:
            - name: VERSION
              value: v8.0